codecov: 
 token: eb32817d-b3ab-4145-a1b0-65742c9ad600
 fixes:
  - "/[A-Za-z]+/runner/work/RustyOptions/RustyOptions/::"
  - "[A-Za-z]:\\[a-z]+\\RustyOptions\\RustyOptions\\src\\RustyOptions\\::src/RustyOptions/"
